apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: frontend-app
  template:
    metadata:
      labels:
        run: frontend-app
    spec:
      containers:
      - name: nodeapp
        image: palanidatabricks/app_node:latest
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  type: NodePort
  ports:
    - name: nodeapp
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30010
  selector:
    app: nodeapp
